### ISSUE TITLE
提升排序（sort） 效率

### ISSUE THREAD

**Issue by NikolasViv** [jianfengye/collection#9]
目前sort实现基于选择排序， 本身选择排序的复杂度 o(n * n), 作者在选择每层最大最小值增加了一层contain方法，实际又是一层循环,复杂度已经到 o(n*n*n)。 

希望改进：
   1、Icollection 增加复制构造.

   2、 基于上边的条件，可以将排序换成快排。复杂度 o(n * log n)

**Comment by jianfengye** [comment]
谢谢反馈，加入到todo了发自我的华为手机-------- 原始邮件 --------主题：[jianfengye/collection] 提升排序（sort） 效率 (#9)发件人：lixiaodong 收件人：jianfengye/collection 抄送：Subscribed 目前sort实现基于选择排序， 本身选择排序的复杂度 o(n * n), 作者在选择每层最大最小值增加了一层contain方法，实际又是一层循环,复杂度已经到 o(nnn)。

希望改进：

1、Icollection 增加复制构造.

2、 基于上边的条件，可以将排序换成快排。复杂度 o(n * log n)



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/jianfengye/collection/issues/9?email_source=notifications\u0026email_token=AAKBM5G2FQKFOW2NQOADJP3PVIYIZA5CNFSM4HMVEWSKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GTSIJ5Q",

"url": "https://github.com/jianfengye/collection/issues/9?email_source=notifications\u0026email_token=AAKBM5G2FQKFOW2NQOADJP3PVIYIZA5CNFSM4HMVEWSKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GTSIJ5Q",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by jianfengye** [comment]
已优化sort，使用快排方式
